/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Partner_rootRouteImport } from './routes/partner/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as PartnerTiersIndexRouteImport } from './routes/partner-tiers/index'
import { Route as PartnerSegmentsIndexRouteImport } from './routes/partner-segments/index'
import { Route as PartnerOperationsIndexRouteImport } from './routes/partner-operations/index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics/index'
import { Route as DirectoryIndexRouteImport } from './routes/directory/index'
import { Route as BillingIndexRouteImport } from './routes/billing/index'
import { Route as AccountMappingIndexRouteImport } from './routes/account-mapping/index'
import { Route as TenantsNewRouteImport } from './routes/tenants/new'
import { Route as TenantsTenantIdRouteImport } from './routes/tenants/$tenantId'
import { Route as SuppliersPurchaseOrdersRouteImport } from './routes/suppliers/purchase-orders'
import { Route as SuppliersInvoicesRouteImport } from './routes/suppliers/invoices'
import { Route as SuppliersCatalogRouteImport } from './routes/suppliers/catalog'
import { Route as PartnersNewRouteImport } from './routes/partners/new'
import { Route as PartnersImportRouteImport } from './routes/partners/import'
import { Route as PartnersHealthRouteImport } from './routes/partners/health'
import { Route as PartnersPartnerIdRouteImport } from './routes/partners/$partnerId'
import { Route as PartnerVerifyEmailRouteImport } from './routes/partner/verify-email'
import { Route as PartnerTimelinesRouteImport } from './routes/partner/timelines'
import { Route as PartnerSettingsRouteImport } from './routes/partner/settings'
import { Route as PartnerServicesRouteImport } from './routes/partner/services'
import { Route as PartnerResendVerificationRouteImport } from './routes/partner/resend-verification'
import { Route as PartnerRegisterRouteImport } from './routes/partner/register'
import { Route as PartnerOnboardingRouteImport } from './routes/partner/onboarding'
import { Route as PartnerLoginRouteImport } from './routes/partner/login'
import { Route as PartnerForgotPasswordRouteImport } from './routes/partner/forgot-password'
import { Route as PartnerEmployeesRouteImport } from './routes/partner/employees'
import { Route as PartnerDocumentsRouteImport } from './routes/partner/documents'
import { Route as PartnerDashboardRouteImport } from './routes/partner/dashboard'
import { Route as PartnerAgreementsRouteImport } from './routes/partner/agreements'
import { Route as OnboardingSettingsRouteImport } from './routes/onboarding/settings'
import { Route as OnboardingAnalyticsRouteImport } from './routes/onboarding/analytics'
import { Route as LogisticsShipmentsRouteImport } from './routes/logistics/shipments'
import { Route as PartnersPartnerIdIndexRouteImport } from './routes/partners/$partnerId/index'
import { Route as PartnerTenantsIndexRouteImport } from './routes/partner/tenants/index'
import { Route as SuppliersPurchaseOrdersPoIdRouteImport } from './routes/suppliers/purchase-orders/$poId'
import { Route as SuppliersInvoicesInvoiceIdRouteImport } from './routes/suppliers/invoices/$invoiceId'
import { Route as PartnersPartnerIdEditRouteImport } from './routes/partners/$partnerId/edit'
import { Route as PartnerTimelinesNewRouteImport } from './routes/partner/timelines.new'
import { Route as PartnerTenantsTenantIdRouteImport } from './routes/partner/tenants.$tenantId'
import { Route as PartnerResetPasswordTokenRouteImport } from './routes/partner/reset-password.$token'
import { Route as PartnerAgreementsAgreementIdRouteImport } from './routes/partner/agreements.$agreementId'
import { Route as LogisticsShipmentsShipmentIdRouteImport } from './routes/logistics/shipments/$shipmentId'
import { Route as PartnersPartnerIdRelationshipsNewRouteImport } from './routes/partners/$partnerId/relationships/new'
import { Route as PartnerTimelinesTimelineIdEditRouteImport } from './routes/partner/timelines.$timelineId.edit'
import { Route as PartnerOnboardingSupplierCatalogRouteImport } from './routes/partner/onboarding/supplier/catalog'
import { Route as PartnerOnboardingSupplierStageRouteImport } from './routes/partner/onboarding/supplier/$stage'
import { Route as PartnerOnboardingServiceStageRouteImport } from './routes/partner/onboarding/service/$stage'

const Partner_rootRoute = Partner_rootRouteImport.update({
  id: '/partner/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerTiersIndexRoute = PartnerTiersIndexRouteImport.update({
  id: '/partner-tiers/',
  path: '/partner-tiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSegmentsIndexRoute = PartnerSegmentsIndexRouteImport.update({
  id: '/partner-segments/',
  path: '/partner-segments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOperationsIndexRoute = PartnerOperationsIndexRouteImport.update({
  id: '/partner-operations/',
  path: '/partner-operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/logistics/',
  path: '/logistics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMappingIndexRoute = AccountMappingIndexRouteImport.update({
  id: '/account-mapping/',
  path: '/account-mapping/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsNewRoute = TenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsTenantIdRoute = TenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersPurchaseOrdersRoute = SuppliersPurchaseOrdersRouteImport.update({
  id: '/suppliers/purchase-orders',
  path: '/suppliers/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersInvoicesRoute = SuppliersInvoicesRouteImport.update({
  id: '/suppliers/invoices',
  path: '/suppliers/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersCatalogRoute = SuppliersCatalogRouteImport.update({
  id: '/suppliers/catalog',
  path: '/suppliers/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersNewRoute = PartnersNewRouteImport.update({
  id: '/partners/new',
  path: '/partners/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersImportRoute = PartnersImportRouteImport.update({
  id: '/partners/import',
  path: '/partners/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersHealthRoute = PartnersHealthRouteImport.update({
  id: '/partners/health',
  path: '/partners/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersPartnerIdRoute = PartnersPartnerIdRouteImport.update({
  id: '/partners/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerVerifyEmailRoute = PartnerVerifyEmailRouteImport.update({
  id: '/partner/verify-email',
  path: '/partner/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerTimelinesRoute = PartnerTimelinesRouteImport.update({
  id: '/partner/timelines',
  path: '/partner/timelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSettingsRoute = PartnerSettingsRouteImport.update({
  id: '/partner/settings',
  path: '/partner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerServicesRoute = PartnerServicesRouteImport.update({
  id: '/partner/services',
  path: '/partner/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerResendVerificationRoute =
  PartnerResendVerificationRouteImport.update({
    id: '/partner/resend-verification',
    path: '/partner/resend-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnerRegisterRoute = PartnerRegisterRouteImport.update({
  id: '/partner/register',
  path: '/partner/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOnboardingRoute = PartnerOnboardingRouteImport.update({
  id: '/partner/onboarding',
  path: '/partner/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner/login',
  path: '/partner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerForgotPasswordRoute = PartnerForgotPasswordRouteImport.update({
  id: '/partner/forgot-password',
  path: '/partner/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerEmployeesRoute = PartnerEmployeesRouteImport.update({
  id: '/partner/employees',
  path: '/partner/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDocumentsRoute = PartnerDocumentsRouteImport.update({
  id: '/partner/documents',
  path: '/partner/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAgreementsRoute = PartnerAgreementsRouteImport.update({
  id: '/partner/agreements',
  path: '/partner/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSettingsRoute = OnboardingSettingsRouteImport.update({
  id: '/onboarding/settings',
  path: '/onboarding/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAnalyticsRoute = OnboardingAnalyticsRouteImport.update({
  id: '/onboarding/analytics',
  path: '/onboarding/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsShipmentsRoute = LogisticsShipmentsRouteImport.update({
  id: '/logistics/shipments',
  path: '/logistics/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersPartnerIdIndexRoute = PartnersPartnerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnersPartnerIdRoute,
} as any)
const PartnerTenantsIndexRoute = PartnerTenantsIndexRouteImport.update({
  id: '/partner/tenants/',
  path: '/partner/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersPurchaseOrdersPoIdRoute =
  SuppliersPurchaseOrdersPoIdRouteImport.update({
    id: '/$poId',
    path: '/$poId',
    getParentRoute: () => SuppliersPurchaseOrdersRoute,
  } as any)
const SuppliersInvoicesInvoiceIdRoute =
  SuppliersInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => SuppliersInvoicesRoute,
  } as any)
const PartnersPartnerIdEditRoute = PartnersPartnerIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PartnersPartnerIdRoute,
} as any)
const PartnerTimelinesNewRoute = PartnerTimelinesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PartnerTimelinesRoute,
} as any)
const PartnerTenantsTenantIdRoute = PartnerTenantsTenantIdRouteImport.update({
  id: '/partner/tenants/$tenantId',
  path: '/partner/tenants/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerResetPasswordTokenRoute =
  PartnerResetPasswordTokenRouteImport.update({
    id: '/partner/reset-password/$token',
    path: '/partner/reset-password/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnerAgreementsAgreementIdRoute =
  PartnerAgreementsAgreementIdRouteImport.update({
    id: '/$agreementId',
    path: '/$agreementId',
    getParentRoute: () => PartnerAgreementsRoute,
  } as any)
const LogisticsShipmentsShipmentIdRoute =
  LogisticsShipmentsShipmentIdRouteImport.update({
    id: '/$shipmentId',
    path: '/$shipmentId',
    getParentRoute: () => LogisticsShipmentsRoute,
  } as any)
const PartnersPartnerIdRelationshipsNewRoute =
  PartnersPartnerIdRelationshipsNewRouteImport.update({
    id: '/relationships/new',
    path: '/relationships/new',
    getParentRoute: () => PartnersPartnerIdRoute,
  } as any)
const PartnerTimelinesTimelineIdEditRoute =
  PartnerTimelinesTimelineIdEditRouteImport.update({
    id: '/$timelineId/edit',
    path: '/$timelineId/edit',
    getParentRoute: () => PartnerTimelinesRoute,
  } as any)
const PartnerOnboardingSupplierCatalogRoute =
  PartnerOnboardingSupplierCatalogRouteImport.update({
    id: '/supplier/catalog',
    path: '/supplier/catalog',
    getParentRoute: () => PartnerOnboardingRoute,
  } as any)
const PartnerOnboardingSupplierStageRoute =
  PartnerOnboardingSupplierStageRouteImport.update({
    id: '/supplier/$stage',
    path: '/supplier/$stage',
    getParentRoute: () => PartnerOnboardingRoute,
  } as any)
const PartnerOnboardingServiceStageRoute =
  PartnerOnboardingServiceStageRouteImport.update({
    id: '/service/$stage',
    path: '/service/$stage',
    getParentRoute: () => PartnerOnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logistics/shipments': typeof LogisticsShipmentsRouteWithChildren
  '/onboarding/analytics': typeof OnboardingAnalyticsRoute
  '/onboarding/settings': typeof OnboardingSettingsRoute
  '/partner': typeof Partner_rootRoute
  '/partner/agreements': typeof PartnerAgreementsRouteWithChildren
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/employees': typeof PartnerEmployeesRoute
  '/partner/forgot-password': typeof PartnerForgotPasswordRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/onboarding': typeof PartnerOnboardingRouteWithChildren
  '/partner/register': typeof PartnerRegisterRoute
  '/partner/resend-verification': typeof PartnerResendVerificationRoute
  '/partner/services': typeof PartnerServicesRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/timelines': typeof PartnerTimelinesRouteWithChildren
  '/partner/verify-email': typeof PartnerVerifyEmailRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRouteWithChildren
  '/partners/health': typeof PartnersHealthRoute
  '/partners/import': typeof PartnersImportRoute
  '/partners/new': typeof PartnersNewRoute
  '/suppliers/catalog': typeof SuppliersCatalogRoute
  '/suppliers/invoices': typeof SuppliersInvoicesRouteWithChildren
  '/suppliers/purchase-orders': typeof SuppliersPurchaseOrdersRouteWithChildren
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/tenants/new': typeof TenantsNewRoute
  '/account-mapping': typeof AccountMappingIndexRoute
  '/billing': typeof BillingIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/partner-operations': typeof PartnerOperationsIndexRoute
  '/partner-segments': typeof PartnerSegmentsIndexRoute
  '/partner-tiers': typeof PartnerTiersIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/logistics/shipments/$shipmentId': typeof LogisticsShipmentsShipmentIdRoute
  '/partner/agreements/$agreementId': typeof PartnerAgreementsAgreementIdRoute
  '/partner/reset-password/$token': typeof PartnerResetPasswordTokenRoute
  '/partner/tenants/$tenantId': typeof PartnerTenantsTenantIdRoute
  '/partner/timelines/new': typeof PartnerTimelinesNewRoute
  '/partners/$partnerId/edit': typeof PartnersPartnerIdEditRoute
  '/suppliers/invoices/$invoiceId': typeof SuppliersInvoicesInvoiceIdRoute
  '/suppliers/purchase-orders/$poId': typeof SuppliersPurchaseOrdersPoIdRoute
  '/partner/tenants': typeof PartnerTenantsIndexRoute
  '/partners/$partnerId/': typeof PartnersPartnerIdIndexRoute
  '/partner/onboarding/service/$stage': typeof PartnerOnboardingServiceStageRoute
  '/partner/onboarding/supplier/$stage': typeof PartnerOnboardingSupplierStageRoute
  '/partner/onboarding/supplier/catalog': typeof PartnerOnboardingSupplierCatalogRoute
  '/partner/timelines/$timelineId/edit': typeof PartnerTimelinesTimelineIdEditRoute
  '/partners/$partnerId/relationships/new': typeof PartnersPartnerIdRelationshipsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logistics/shipments': typeof LogisticsShipmentsRouteWithChildren
  '/onboarding/analytics': typeof OnboardingAnalyticsRoute
  '/onboarding/settings': typeof OnboardingSettingsRoute
  '/partner': typeof Partner_rootRoute
  '/partner/agreements': typeof PartnerAgreementsRouteWithChildren
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/employees': typeof PartnerEmployeesRoute
  '/partner/forgot-password': typeof PartnerForgotPasswordRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/onboarding': typeof PartnerOnboardingRouteWithChildren
  '/partner/register': typeof PartnerRegisterRoute
  '/partner/resend-verification': typeof PartnerResendVerificationRoute
  '/partner/services': typeof PartnerServicesRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/timelines': typeof PartnerTimelinesRouteWithChildren
  '/partner/verify-email': typeof PartnerVerifyEmailRoute
  '/partners/health': typeof PartnersHealthRoute
  '/partners/import': typeof PartnersImportRoute
  '/partners/new': typeof PartnersNewRoute
  '/suppliers/catalog': typeof SuppliersCatalogRoute
  '/suppliers/invoices': typeof SuppliersInvoicesRouteWithChildren
  '/suppliers/purchase-orders': typeof SuppliersPurchaseOrdersRouteWithChildren
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/tenants/new': typeof TenantsNewRoute
  '/account-mapping': typeof AccountMappingIndexRoute
  '/billing': typeof BillingIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/partner-operations': typeof PartnerOperationsIndexRoute
  '/partner-segments': typeof PartnerSegmentsIndexRoute
  '/partner-tiers': typeof PartnerTiersIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/logistics/shipments/$shipmentId': typeof LogisticsShipmentsShipmentIdRoute
  '/partner/agreements/$agreementId': typeof PartnerAgreementsAgreementIdRoute
  '/partner/reset-password/$token': typeof PartnerResetPasswordTokenRoute
  '/partner/tenants/$tenantId': typeof PartnerTenantsTenantIdRoute
  '/partner/timelines/new': typeof PartnerTimelinesNewRoute
  '/partners/$partnerId/edit': typeof PartnersPartnerIdEditRoute
  '/suppliers/invoices/$invoiceId': typeof SuppliersInvoicesInvoiceIdRoute
  '/suppliers/purchase-orders/$poId': typeof SuppliersPurchaseOrdersPoIdRoute
  '/partner/tenants': typeof PartnerTenantsIndexRoute
  '/partners/$partnerId': typeof PartnersPartnerIdIndexRoute
  '/partner/onboarding/service/$stage': typeof PartnerOnboardingServiceStageRoute
  '/partner/onboarding/supplier/$stage': typeof PartnerOnboardingSupplierStageRoute
  '/partner/onboarding/supplier/catalog': typeof PartnerOnboardingSupplierCatalogRoute
  '/partner/timelines/$timelineId/edit': typeof PartnerTimelinesTimelineIdEditRoute
  '/partners/$partnerId/relationships/new': typeof PartnersPartnerIdRelationshipsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logistics/shipments': typeof LogisticsShipmentsRouteWithChildren
  '/onboarding/analytics': typeof OnboardingAnalyticsRoute
  '/onboarding/settings': typeof OnboardingSettingsRoute
  '/partner/__root': typeof Partner_rootRoute
  '/partner/agreements': typeof PartnerAgreementsRouteWithChildren
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/employees': typeof PartnerEmployeesRoute
  '/partner/forgot-password': typeof PartnerForgotPasswordRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/onboarding': typeof PartnerOnboardingRouteWithChildren
  '/partner/register': typeof PartnerRegisterRoute
  '/partner/resend-verification': typeof PartnerResendVerificationRoute
  '/partner/services': typeof PartnerServicesRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/timelines': typeof PartnerTimelinesRouteWithChildren
  '/partner/verify-email': typeof PartnerVerifyEmailRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRouteWithChildren
  '/partners/health': typeof PartnersHealthRoute
  '/partners/import': typeof PartnersImportRoute
  '/partners/new': typeof PartnersNewRoute
  '/suppliers/catalog': typeof SuppliersCatalogRoute
  '/suppliers/invoices': typeof SuppliersInvoicesRouteWithChildren
  '/suppliers/purchase-orders': typeof SuppliersPurchaseOrdersRouteWithChildren
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/tenants/new': typeof TenantsNewRoute
  '/account-mapping/': typeof AccountMappingIndexRoute
  '/billing/': typeof BillingIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/partner-operations/': typeof PartnerOperationsIndexRoute
  '/partner-segments/': typeof PartnerSegmentsIndexRoute
  '/partner-tiers/': typeof PartnerTiersIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/logistics/shipments/$shipmentId': typeof LogisticsShipmentsShipmentIdRoute
  '/partner/agreements/$agreementId': typeof PartnerAgreementsAgreementIdRoute
  '/partner/reset-password/$token': typeof PartnerResetPasswordTokenRoute
  '/partner/tenants/$tenantId': typeof PartnerTenantsTenantIdRoute
  '/partner/timelines/new': typeof PartnerTimelinesNewRoute
  '/partners/$partnerId/edit': typeof PartnersPartnerIdEditRoute
  '/suppliers/invoices/$invoiceId': typeof SuppliersInvoicesInvoiceIdRoute
  '/suppliers/purchase-orders/$poId': typeof SuppliersPurchaseOrdersPoIdRoute
  '/partner/tenants/': typeof PartnerTenantsIndexRoute
  '/partners/$partnerId/': typeof PartnersPartnerIdIndexRoute
  '/partner/onboarding/service/$stage': typeof PartnerOnboardingServiceStageRoute
  '/partner/onboarding/supplier/$stage': typeof PartnerOnboardingSupplierStageRoute
  '/partner/onboarding/supplier/catalog': typeof PartnerOnboardingSupplierCatalogRoute
  '/partner/timelines/$timelineId/edit': typeof PartnerTimelinesTimelineIdEditRoute
  '/partners/$partnerId/relationships/new': typeof PartnersPartnerIdRelationshipsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logistics/shipments'
    | '/onboarding/analytics'
    | '/onboarding/settings'
    | '/partner'
    | '/partner/agreements'
    | '/partner/dashboard'
    | '/partner/documents'
    | '/partner/employees'
    | '/partner/forgot-password'
    | '/partner/login'
    | '/partner/onboarding'
    | '/partner/register'
    | '/partner/resend-verification'
    | '/partner/services'
    | '/partner/settings'
    | '/partner/timelines'
    | '/partner/verify-email'
    | '/partners/$partnerId'
    | '/partners/health'
    | '/partners/import'
    | '/partners/new'
    | '/suppliers/catalog'
    | '/suppliers/invoices'
    | '/suppliers/purchase-orders'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/account-mapping'
    | '/billing'
    | '/directory'
    | '/logistics'
    | '/partner-operations'
    | '/partner-segments'
    | '/partner-tiers'
    | '/partners'
    | '/suppliers'
    | '/tenants'
    | '/logistics/shipments/$shipmentId'
    | '/partner/agreements/$agreementId'
    | '/partner/reset-password/$token'
    | '/partner/tenants/$tenantId'
    | '/partner/timelines/new'
    | '/partners/$partnerId/edit'
    | '/suppliers/invoices/$invoiceId'
    | '/suppliers/purchase-orders/$poId'
    | '/partner/tenants'
    | '/partners/$partnerId/'
    | '/partner/onboarding/service/$stage'
    | '/partner/onboarding/supplier/$stage'
    | '/partner/onboarding/supplier/catalog'
    | '/partner/timelines/$timelineId/edit'
    | '/partners/$partnerId/relationships/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logistics/shipments'
    | '/onboarding/analytics'
    | '/onboarding/settings'
    | '/partner'
    | '/partner/agreements'
    | '/partner/dashboard'
    | '/partner/documents'
    | '/partner/employees'
    | '/partner/forgot-password'
    | '/partner/login'
    | '/partner/onboarding'
    | '/partner/register'
    | '/partner/resend-verification'
    | '/partner/services'
    | '/partner/settings'
    | '/partner/timelines'
    | '/partner/verify-email'
    | '/partners/health'
    | '/partners/import'
    | '/partners/new'
    | '/suppliers/catalog'
    | '/suppliers/invoices'
    | '/suppliers/purchase-orders'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/account-mapping'
    | '/billing'
    | '/directory'
    | '/logistics'
    | '/partner-operations'
    | '/partner-segments'
    | '/partner-tiers'
    | '/partners'
    | '/suppliers'
    | '/tenants'
    | '/logistics/shipments/$shipmentId'
    | '/partner/agreements/$agreementId'
    | '/partner/reset-password/$token'
    | '/partner/tenants/$tenantId'
    | '/partner/timelines/new'
    | '/partners/$partnerId/edit'
    | '/suppliers/invoices/$invoiceId'
    | '/suppliers/purchase-orders/$poId'
    | '/partner/tenants'
    | '/partners/$partnerId'
    | '/partner/onboarding/service/$stage'
    | '/partner/onboarding/supplier/$stage'
    | '/partner/onboarding/supplier/catalog'
    | '/partner/timelines/$timelineId/edit'
    | '/partners/$partnerId/relationships/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logistics/shipments'
    | '/onboarding/analytics'
    | '/onboarding/settings'
    | '/partner/__root'
    | '/partner/agreements'
    | '/partner/dashboard'
    | '/partner/documents'
    | '/partner/employees'
    | '/partner/forgot-password'
    | '/partner/login'
    | '/partner/onboarding'
    | '/partner/register'
    | '/partner/resend-verification'
    | '/partner/services'
    | '/partner/settings'
    | '/partner/timelines'
    | '/partner/verify-email'
    | '/partners/$partnerId'
    | '/partners/health'
    | '/partners/import'
    | '/partners/new'
    | '/suppliers/catalog'
    | '/suppliers/invoices'
    | '/suppliers/purchase-orders'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/account-mapping/'
    | '/billing/'
    | '/directory/'
    | '/logistics/'
    | '/partner-operations/'
    | '/partner-segments/'
    | '/partner-tiers/'
    | '/partners/'
    | '/suppliers/'
    | '/tenants/'
    | '/logistics/shipments/$shipmentId'
    | '/partner/agreements/$agreementId'
    | '/partner/reset-password/$token'
    | '/partner/tenants/$tenantId'
    | '/partner/timelines/new'
    | '/partners/$partnerId/edit'
    | '/suppliers/invoices/$invoiceId'
    | '/suppliers/purchase-orders/$poId'
    | '/partner/tenants/'
    | '/partners/$partnerId/'
    | '/partner/onboarding/service/$stage'
    | '/partner/onboarding/supplier/$stage'
    | '/partner/onboarding/supplier/catalog'
    | '/partner/timelines/$timelineId/edit'
    | '/partners/$partnerId/relationships/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogisticsShipmentsRoute: typeof LogisticsShipmentsRouteWithChildren
  OnboardingAnalyticsRoute: typeof OnboardingAnalyticsRoute
  OnboardingSettingsRoute: typeof OnboardingSettingsRoute
  Partner_rootRoute: typeof Partner_rootRoute
  PartnerAgreementsRoute: typeof PartnerAgreementsRouteWithChildren
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PartnerDocumentsRoute: typeof PartnerDocumentsRoute
  PartnerEmployeesRoute: typeof PartnerEmployeesRoute
  PartnerForgotPasswordRoute: typeof PartnerForgotPasswordRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PartnerOnboardingRoute: typeof PartnerOnboardingRouteWithChildren
  PartnerRegisterRoute: typeof PartnerRegisterRoute
  PartnerResendVerificationRoute: typeof PartnerResendVerificationRoute
  PartnerServicesRoute: typeof PartnerServicesRoute
  PartnerSettingsRoute: typeof PartnerSettingsRoute
  PartnerTimelinesRoute: typeof PartnerTimelinesRouteWithChildren
  PartnerVerifyEmailRoute: typeof PartnerVerifyEmailRoute
  PartnersPartnerIdRoute: typeof PartnersPartnerIdRouteWithChildren
  PartnersHealthRoute: typeof PartnersHealthRoute
  PartnersImportRoute: typeof PartnersImportRoute
  PartnersNewRoute: typeof PartnersNewRoute
  SuppliersCatalogRoute: typeof SuppliersCatalogRoute
  SuppliersInvoicesRoute: typeof SuppliersInvoicesRouteWithChildren
  SuppliersPurchaseOrdersRoute: typeof SuppliersPurchaseOrdersRouteWithChildren
  TenantsTenantIdRoute: typeof TenantsTenantIdRoute
  TenantsNewRoute: typeof TenantsNewRoute
  AccountMappingIndexRoute: typeof AccountMappingIndexRoute
  BillingIndexRoute: typeof BillingIndexRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  LogisticsIndexRoute: typeof LogisticsIndexRoute
  PartnerOperationsIndexRoute: typeof PartnerOperationsIndexRoute
  PartnerSegmentsIndexRoute: typeof PartnerSegmentsIndexRoute
  PartnerTiersIndexRoute: typeof PartnerTiersIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  PartnerResetPasswordTokenRoute: typeof PartnerResetPasswordTokenRoute
  PartnerTenantsTenantIdRoute: typeof PartnerTenantsTenantIdRoute
  PartnerTenantsIndexRoute: typeof PartnerTenantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner/__root': {
      id: '/partner/__root'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof Partner_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-tiers/': {
      id: '/partner-tiers/'
      path: '/partner-tiers'
      fullPath: '/partner-tiers'
      preLoaderRoute: typeof PartnerTiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-segments/': {
      id: '/partner-segments/'
      path: '/partner-segments'
      fullPath: '/partner-segments'
      preLoaderRoute: typeof PartnerSegmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-operations/': {
      id: '/partner-operations/'
      path: '/partner-operations'
      fullPath: '/partner-operations'
      preLoaderRoute: typeof PartnerOperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-mapping/': {
      id: '/account-mapping/'
      path: '/account-mapping'
      fullPath: '/account-mapping'
      preLoaderRoute: typeof AccountMappingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/new': {
      id: '/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof TenantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$tenantId': {
      id: '/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof TenantsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/purchase-orders': {
      id: '/suppliers/purchase-orders'
      path: '/suppliers/purchase-orders'
      fullPath: '/suppliers/purchase-orders'
      preLoaderRoute: typeof SuppliersPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/invoices': {
      id: '/suppliers/invoices'
      path: '/suppliers/invoices'
      fullPath: '/suppliers/invoices'
      preLoaderRoute: typeof SuppliersInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/catalog': {
      id: '/suppliers/catalog'
      path: '/suppliers/catalog'
      fullPath: '/suppliers/catalog'
      preLoaderRoute: typeof SuppliersCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/new': {
      id: '/partners/new'
      path: '/partners/new'
      fullPath: '/partners/new'
      preLoaderRoute: typeof PartnersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/import': {
      id: '/partners/import'
      path: '/partners/import'
      fullPath: '/partners/import'
      preLoaderRoute: typeof PartnersImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/health': {
      id: '/partners/health'
      path: '/partners/health'
      fullPath: '/partners/health'
      preLoaderRoute: typeof PartnersHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$partnerId': {
      id: '/partners/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof PartnersPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/verify-email': {
      id: '/partner/verify-email'
      path: '/partner/verify-email'
      fullPath: '/partner/verify-email'
      preLoaderRoute: typeof PartnerVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/timelines': {
      id: '/partner/timelines'
      path: '/partner/timelines'
      fullPath: '/partner/timelines'
      preLoaderRoute: typeof PartnerTimelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/settings': {
      id: '/partner/settings'
      path: '/partner/settings'
      fullPath: '/partner/settings'
      preLoaderRoute: typeof PartnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/services': {
      id: '/partner/services'
      path: '/partner/services'
      fullPath: '/partner/services'
      preLoaderRoute: typeof PartnerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/resend-verification': {
      id: '/partner/resend-verification'
      path: '/partner/resend-verification'
      fullPath: '/partner/resend-verification'
      preLoaderRoute: typeof PartnerResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/register': {
      id: '/partner/register'
      path: '/partner/register'
      fullPath: '/partner/register'
      preLoaderRoute: typeof PartnerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/onboarding': {
      id: '/partner/onboarding'
      path: '/partner/onboarding'
      fullPath: '/partner/onboarding'
      preLoaderRoute: typeof PartnerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/login': {
      id: '/partner/login'
      path: '/partner/login'
      fullPath: '/partner/login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/forgot-password': {
      id: '/partner/forgot-password'
      path: '/partner/forgot-password'
      fullPath: '/partner/forgot-password'
      preLoaderRoute: typeof PartnerForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/employees': {
      id: '/partner/employees'
      path: '/partner/employees'
      fullPath: '/partner/employees'
      preLoaderRoute: typeof PartnerEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/documents': {
      id: '/partner/documents'
      path: '/partner/documents'
      fullPath: '/partner/documents'
      preLoaderRoute: typeof PartnerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/agreements': {
      id: '/partner/agreements'
      path: '/partner/agreements'
      fullPath: '/partner/agreements'
      preLoaderRoute: typeof PartnerAgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/settings': {
      id: '/onboarding/settings'
      path: '/onboarding/settings'
      fullPath: '/onboarding/settings'
      preLoaderRoute: typeof OnboardingSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/analytics': {
      id: '/onboarding/analytics'
      path: '/onboarding/analytics'
      fullPath: '/onboarding/analytics'
      preLoaderRoute: typeof OnboardingAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/shipments': {
      id: '/logistics/shipments'
      path: '/logistics/shipments'
      fullPath: '/logistics/shipments'
      preLoaderRoute: typeof LogisticsShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$partnerId/': {
      id: '/partners/$partnerId/'
      path: '/'
      fullPath: '/partners/$partnerId/'
      preLoaderRoute: typeof PartnersPartnerIdIndexRouteImport
      parentRoute: typeof PartnersPartnerIdRoute
    }
    '/partner/tenants/': {
      id: '/partner/tenants/'
      path: '/partner/tenants'
      fullPath: '/partner/tenants'
      preLoaderRoute: typeof PartnerTenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/purchase-orders/$poId': {
      id: '/suppliers/purchase-orders/$poId'
      path: '/$poId'
      fullPath: '/suppliers/purchase-orders/$poId'
      preLoaderRoute: typeof SuppliersPurchaseOrdersPoIdRouteImport
      parentRoute: typeof SuppliersPurchaseOrdersRoute
    }
    '/suppliers/invoices/$invoiceId': {
      id: '/suppliers/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/suppliers/invoices/$invoiceId'
      preLoaderRoute: typeof SuppliersInvoicesInvoiceIdRouteImport
      parentRoute: typeof SuppliersInvoicesRoute
    }
    '/partners/$partnerId/edit': {
      id: '/partners/$partnerId/edit'
      path: '/edit'
      fullPath: '/partners/$partnerId/edit'
      preLoaderRoute: typeof PartnersPartnerIdEditRouteImport
      parentRoute: typeof PartnersPartnerIdRoute
    }
    '/partner/timelines/new': {
      id: '/partner/timelines/new'
      path: '/new'
      fullPath: '/partner/timelines/new'
      preLoaderRoute: typeof PartnerTimelinesNewRouteImport
      parentRoute: typeof PartnerTimelinesRoute
    }
    '/partner/tenants/$tenantId': {
      id: '/partner/tenants/$tenantId'
      path: '/partner/tenants/$tenantId'
      fullPath: '/partner/tenants/$tenantId'
      preLoaderRoute: typeof PartnerTenantsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/reset-password/$token': {
      id: '/partner/reset-password/$token'
      path: '/partner/reset-password/$token'
      fullPath: '/partner/reset-password/$token'
      preLoaderRoute: typeof PartnerResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/agreements/$agreementId': {
      id: '/partner/agreements/$agreementId'
      path: '/$agreementId'
      fullPath: '/partner/agreements/$agreementId'
      preLoaderRoute: typeof PartnerAgreementsAgreementIdRouteImport
      parentRoute: typeof PartnerAgreementsRoute
    }
    '/logistics/shipments/$shipmentId': {
      id: '/logistics/shipments/$shipmentId'
      path: '/$shipmentId'
      fullPath: '/logistics/shipments/$shipmentId'
      preLoaderRoute: typeof LogisticsShipmentsShipmentIdRouteImport
      parentRoute: typeof LogisticsShipmentsRoute
    }
    '/partners/$partnerId/relationships/new': {
      id: '/partners/$partnerId/relationships/new'
      path: '/relationships/new'
      fullPath: '/partners/$partnerId/relationships/new'
      preLoaderRoute: typeof PartnersPartnerIdRelationshipsNewRouteImport
      parentRoute: typeof PartnersPartnerIdRoute
    }
    '/partner/timelines/$timelineId/edit': {
      id: '/partner/timelines/$timelineId/edit'
      path: '/$timelineId/edit'
      fullPath: '/partner/timelines/$timelineId/edit'
      preLoaderRoute: typeof PartnerTimelinesTimelineIdEditRouteImport
      parentRoute: typeof PartnerTimelinesRoute
    }
    '/partner/onboarding/supplier/catalog': {
      id: '/partner/onboarding/supplier/catalog'
      path: '/supplier/catalog'
      fullPath: '/partner/onboarding/supplier/catalog'
      preLoaderRoute: typeof PartnerOnboardingSupplierCatalogRouteImport
      parentRoute: typeof PartnerOnboardingRoute
    }
    '/partner/onboarding/supplier/$stage': {
      id: '/partner/onboarding/supplier/$stage'
      path: '/supplier/$stage'
      fullPath: '/partner/onboarding/supplier/$stage'
      preLoaderRoute: typeof PartnerOnboardingSupplierStageRouteImport
      parentRoute: typeof PartnerOnboardingRoute
    }
    '/partner/onboarding/service/$stage': {
      id: '/partner/onboarding/service/$stage'
      path: '/service/$stage'
      fullPath: '/partner/onboarding/service/$stage'
      preLoaderRoute: typeof PartnerOnboardingServiceStageRouteImport
      parentRoute: typeof PartnerOnboardingRoute
    }
  }
}

interface LogisticsShipmentsRouteChildren {
  LogisticsShipmentsShipmentIdRoute: typeof LogisticsShipmentsShipmentIdRoute
}

const LogisticsShipmentsRouteChildren: LogisticsShipmentsRouteChildren = {
  LogisticsShipmentsShipmentIdRoute: LogisticsShipmentsShipmentIdRoute,
}

const LogisticsShipmentsRouteWithChildren =
  LogisticsShipmentsRoute._addFileChildren(LogisticsShipmentsRouteChildren)

interface PartnerAgreementsRouteChildren {
  PartnerAgreementsAgreementIdRoute: typeof PartnerAgreementsAgreementIdRoute
}

const PartnerAgreementsRouteChildren: PartnerAgreementsRouteChildren = {
  PartnerAgreementsAgreementIdRoute: PartnerAgreementsAgreementIdRoute,
}

const PartnerAgreementsRouteWithChildren =
  PartnerAgreementsRoute._addFileChildren(PartnerAgreementsRouteChildren)

interface PartnerOnboardingRouteChildren {
  PartnerOnboardingServiceStageRoute: typeof PartnerOnboardingServiceStageRoute
  PartnerOnboardingSupplierStageRoute: typeof PartnerOnboardingSupplierStageRoute
  PartnerOnboardingSupplierCatalogRoute: typeof PartnerOnboardingSupplierCatalogRoute
}

const PartnerOnboardingRouteChildren: PartnerOnboardingRouteChildren = {
  PartnerOnboardingServiceStageRoute: PartnerOnboardingServiceStageRoute,
  PartnerOnboardingSupplierStageRoute: PartnerOnboardingSupplierStageRoute,
  PartnerOnboardingSupplierCatalogRoute: PartnerOnboardingSupplierCatalogRoute,
}

const PartnerOnboardingRouteWithChildren =
  PartnerOnboardingRoute._addFileChildren(PartnerOnboardingRouteChildren)

interface PartnerTimelinesRouteChildren {
  PartnerTimelinesNewRoute: typeof PartnerTimelinesNewRoute
  PartnerTimelinesTimelineIdEditRoute: typeof PartnerTimelinesTimelineIdEditRoute
}

const PartnerTimelinesRouteChildren: PartnerTimelinesRouteChildren = {
  PartnerTimelinesNewRoute: PartnerTimelinesNewRoute,
  PartnerTimelinesTimelineIdEditRoute: PartnerTimelinesTimelineIdEditRoute,
}

const PartnerTimelinesRouteWithChildren =
  PartnerTimelinesRoute._addFileChildren(PartnerTimelinesRouteChildren)

interface PartnersPartnerIdRouteChildren {
  PartnersPartnerIdEditRoute: typeof PartnersPartnerIdEditRoute
  PartnersPartnerIdIndexRoute: typeof PartnersPartnerIdIndexRoute
  PartnersPartnerIdRelationshipsNewRoute: typeof PartnersPartnerIdRelationshipsNewRoute
}

const PartnersPartnerIdRouteChildren: PartnersPartnerIdRouteChildren = {
  PartnersPartnerIdEditRoute: PartnersPartnerIdEditRoute,
  PartnersPartnerIdIndexRoute: PartnersPartnerIdIndexRoute,
  PartnersPartnerIdRelationshipsNewRoute:
    PartnersPartnerIdRelationshipsNewRoute,
}

const PartnersPartnerIdRouteWithChildren =
  PartnersPartnerIdRoute._addFileChildren(PartnersPartnerIdRouteChildren)

interface SuppliersInvoicesRouteChildren {
  SuppliersInvoicesInvoiceIdRoute: typeof SuppliersInvoicesInvoiceIdRoute
}

const SuppliersInvoicesRouteChildren: SuppliersInvoicesRouteChildren = {
  SuppliersInvoicesInvoiceIdRoute: SuppliersInvoicesInvoiceIdRoute,
}

const SuppliersInvoicesRouteWithChildren =
  SuppliersInvoicesRoute._addFileChildren(SuppliersInvoicesRouteChildren)

interface SuppliersPurchaseOrdersRouteChildren {
  SuppliersPurchaseOrdersPoIdRoute: typeof SuppliersPurchaseOrdersPoIdRoute
}

const SuppliersPurchaseOrdersRouteChildren: SuppliersPurchaseOrdersRouteChildren =
  {
    SuppliersPurchaseOrdersPoIdRoute: SuppliersPurchaseOrdersPoIdRoute,
  }

const SuppliersPurchaseOrdersRouteWithChildren =
  SuppliersPurchaseOrdersRoute._addFileChildren(
    SuppliersPurchaseOrdersRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogisticsShipmentsRoute: LogisticsShipmentsRouteWithChildren,
  OnboardingAnalyticsRoute: OnboardingAnalyticsRoute,
  OnboardingSettingsRoute: OnboardingSettingsRoute,
  Partner_rootRoute: Partner_rootRoute,
  PartnerAgreementsRoute: PartnerAgreementsRouteWithChildren,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PartnerDocumentsRoute: PartnerDocumentsRoute,
  PartnerEmployeesRoute: PartnerEmployeesRoute,
  PartnerForgotPasswordRoute: PartnerForgotPasswordRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PartnerOnboardingRoute: PartnerOnboardingRouteWithChildren,
  PartnerRegisterRoute: PartnerRegisterRoute,
  PartnerResendVerificationRoute: PartnerResendVerificationRoute,
  PartnerServicesRoute: PartnerServicesRoute,
  PartnerSettingsRoute: PartnerSettingsRoute,
  PartnerTimelinesRoute: PartnerTimelinesRouteWithChildren,
  PartnerVerifyEmailRoute: PartnerVerifyEmailRoute,
  PartnersPartnerIdRoute: PartnersPartnerIdRouteWithChildren,
  PartnersHealthRoute: PartnersHealthRoute,
  PartnersImportRoute: PartnersImportRoute,
  PartnersNewRoute: PartnersNewRoute,
  SuppliersCatalogRoute: SuppliersCatalogRoute,
  SuppliersInvoicesRoute: SuppliersInvoicesRouteWithChildren,
  SuppliersPurchaseOrdersRoute: SuppliersPurchaseOrdersRouteWithChildren,
  TenantsTenantIdRoute: TenantsTenantIdRoute,
  TenantsNewRoute: TenantsNewRoute,
  AccountMappingIndexRoute: AccountMappingIndexRoute,
  BillingIndexRoute: BillingIndexRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  LogisticsIndexRoute: LogisticsIndexRoute,
  PartnerOperationsIndexRoute: PartnerOperationsIndexRoute,
  PartnerSegmentsIndexRoute: PartnerSegmentsIndexRoute,
  PartnerTiersIndexRoute: PartnerTiersIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  PartnerResetPasswordTokenRoute: PartnerResetPasswordTokenRoute,
  PartnerTenantsTenantIdRoute: PartnerTenantsTenantIdRoute,
  PartnerTenantsIndexRoute: PartnerTenantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
